version: 0.0
os: linux
files:
  - source: /
    destination: /app
hooks:
  BeforeInstall:
    - location: scripts/stop-container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/build-and-start-container.sh
      timeout: 300
      runas: root
